// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: mode_usage.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModeUsageService_GetPopularMode_FullMethodName = "/multiplayer.ModeUsageService/GetPopularMode"
)

// ModeUsageServiceClient is the client API for ModeUsageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModeUsageServiceClient interface {
	GetPopularMode(ctx context.Context, in *ModeUsageRequest, opts ...grpc.CallOption) (*ModeUsageResponse, error)
}

type modeUsageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModeUsageServiceClient(cc grpc.ClientConnInterface) ModeUsageServiceClient {
	return &modeUsageServiceClient{cc}
}

func (c *modeUsageServiceClient) GetPopularMode(ctx context.Context, in *ModeUsageRequest, opts ...grpc.CallOption) (*ModeUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModeUsageResponse)
	err := c.cc.Invoke(ctx, ModeUsageService_GetPopularMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModeUsageServiceServer is the server API for ModeUsageService service.
// All implementations must embed UnimplementedModeUsageServiceServer
// for forward compatibility.
type ModeUsageServiceServer interface {
	GetPopularMode(context.Context, *ModeUsageRequest) (*ModeUsageResponse, error)
	mustEmbedUnimplementedModeUsageServiceServer()
}

// UnimplementedModeUsageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModeUsageServiceServer struct{}

func (UnimplementedModeUsageServiceServer) GetPopularMode(context.Context, *ModeUsageRequest) (*ModeUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPopularMode not implemented")
}
func (UnimplementedModeUsageServiceServer) mustEmbedUnimplementedModeUsageServiceServer() {}
func (UnimplementedModeUsageServiceServer) testEmbeddedByValue()                          {}

// UnsafeModeUsageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModeUsageServiceServer will
// result in compilation errors.
type UnsafeModeUsageServiceServer interface {
	mustEmbedUnimplementedModeUsageServiceServer()
}

func RegisterModeUsageServiceServer(s grpc.ServiceRegistrar, srv ModeUsageServiceServer) {
	// If the following call pancis, it indicates UnimplementedModeUsageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModeUsageService_ServiceDesc, srv)
}

func _ModeUsageService_GetPopularMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModeUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModeUsageServiceServer).GetPopularMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModeUsageService_GetPopularMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModeUsageServiceServer).GetPopularMode(ctx, req.(*ModeUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModeUsageService_ServiceDesc is the grpc.ServiceDesc for ModeUsageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModeUsageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "multiplayer.ModeUsageService",
	HandlerType: (*ModeUsageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPopularMode",
			Handler:    _ModeUsageService_GetPopularMode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mode_usage.proto",
}
