// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: mode_usage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModeUsageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AreaCode string `protobuf:"bytes,1,opt,name=area_code,json=areaCode,proto3" json:"area_code,omitempty"`
}

func (x *ModeUsageRequest) Reset() {
	*x = ModeUsageRequest{}
	mi := &file_mode_usage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeUsageRequest) ProtoMessage() {}

func (x *ModeUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mode_usage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeUsageRequest.ProtoReflect.Descriptor instead.
func (*ModeUsageRequest) Descriptor() ([]byte, []int) {
	return file_mode_usage_proto_rawDescGZIP(), []int{0}
}

func (x *ModeUsageRequest) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

type ModeUsageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MostPlayedMode string `protobuf:"bytes,1,opt,name=most_played_mode,json=mostPlayedMode,proto3" json:"most_played_mode,omitempty"`
	PlayerCount    int32  `protobuf:"varint,2,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
}

func (x *ModeUsageResponse) Reset() {
	*x = ModeUsageResponse{}
	mi := &file_mode_usage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeUsageResponse) ProtoMessage() {}

func (x *ModeUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mode_usage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeUsageResponse.ProtoReflect.Descriptor instead.
func (*ModeUsageResponse) Descriptor() ([]byte, []int) {
	return file_mode_usage_proto_rawDescGZIP(), []int{1}
}

func (x *ModeUsageResponse) GetMostPlayedMode() string {
	if x != nil {
		return x.MostPlayedMode
	}
	return ""
}

func (x *ModeUsageResponse) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

var File_mode_usage_proto protoreflect.FileDescriptor

var file_mode_usage_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x6f, 0x64, 0x65, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22,
	0x2f, 0x0a, 0x10, 0x4d, 0x6f, 0x64, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65,
	0x22, 0x60, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x64, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x6d, 0x6f, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x32, 0x63, 0x0a, 0x10, 0x4d, 0x6f, 0x64, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x70,
	0x75, 0x6c, 0x61, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1e, 0x5a, 0x1c, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x2d, 0x75, 0x73, 0x61, 0x67,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mode_usage_proto_rawDescOnce sync.Once
	file_mode_usage_proto_rawDescData = file_mode_usage_proto_rawDesc
)

func file_mode_usage_proto_rawDescGZIP() []byte {
	file_mode_usage_proto_rawDescOnce.Do(func() {
		file_mode_usage_proto_rawDescData = protoimpl.X.CompressGZIP(file_mode_usage_proto_rawDescData)
	})
	return file_mode_usage_proto_rawDescData
}

var file_mode_usage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mode_usage_proto_goTypes = []any{
	(*ModeUsageRequest)(nil),  // 0: multiplayer.ModeUsageRequest
	(*ModeUsageResponse)(nil), // 1: multiplayer.ModeUsageResponse
}
var file_mode_usage_proto_depIdxs = []int32{
	0, // 0: multiplayer.ModeUsageService.GetPopularMode:input_type -> multiplayer.ModeUsageRequest
	1, // 1: multiplayer.ModeUsageService.GetPopularMode:output_type -> multiplayer.ModeUsageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mode_usage_proto_init() }
func file_mode_usage_proto_init() {
	if File_mode_usage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mode_usage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mode_usage_proto_goTypes,
		DependencyIndexes: file_mode_usage_proto_depIdxs,
		MessageInfos:      file_mode_usage_proto_msgTypes,
	}.Build()
	File_mode_usage_proto = out.File
	file_mode_usage_proto_rawDesc = nil
	file_mode_usage_proto_goTypes = nil
	file_mode_usage_proto_depIdxs = nil
}
